version: '3'
services:
  stock-server:
    build:
      context: .
      dockerfile: ./Dockerfile_server
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - mynetwork

  stock-client:
    build:
      context: .
      dockerfile: ./Dockerfile_client
    deploy:
      mode: global
    networks:
      - mynetwork
    
  nginx-load-balancer:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./load_balancer:/etc/nginx/conf.d
    depends_on:
      - stock-server
    networks:
      - mynetwork

networks:
  mynetwork: