# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY client.py /app

# Install required Python packages
RUN pip install rpyc yfinance

# Run the client script when the container launches
CMD ["python", "client.py"]
