version: '3'
services:
  stock-server:
    image: stock-server
    deploy:
      replicas: 3

  stock-client:
    image: stock-client
    depends_on:
      - nginx-load-balancer

  nginx-load-balancer:
    image: nginx
    volumes:
      - ./load_balancer:/etc/nginx/conf.d
    depends_on:
      - stock-server
